# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

def shared_pods
  pod 'AppCenter'
  pod 'Gestalt', '~> 2.0.0'
  pod 'Hue'
  pod 'RealmSwift'
  pod 'SwiftLint'
end

target 'Kelpie' do
  shared_pods
  pod 'Former'
  pod 'KeyboardObserver', '~> 2.1'
  pod 'ReadabilityKit'
  pod 'SPStorkController'
end
